version: '3.1'

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8094:80
    environment:
      YOURLS_DB_PASS: allen123
      YOURLS_SITE: http://localhost:8094
      YOURLS_USER: lileililiwen
      YOURLS_PASS: 2660471cxq

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: allen123
      MYSQL_DATABASE: yourls