version: "3"

services:
  flarum:
   image: mondedie/flarum:latest
   container_name: flarum
   environment:
    - PHP_EXTENSIONS=gmp session brotli
   env_file:
    - ./flarum.env
   volumes:
    - /d/docker-volumes/flarum/assets:/flarum/app/public/assets
    - /d/docker-volumes/flarum/extensions:/flarum/app/extensions
    - /d/docker-volumes/flarum/storage/logs:/flarum/app/storage/logs
    - /d/docker-volumes/flarum/nginx:/etc/nginx/flarum
   ports:
    - 8081:8888
   depends_on:
    - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarum
    volumes:
      - /d/docker-volumes/flarum/mysql/db:/var/lib/mysql