version: '3.5'

services:
  nodebb:
    image: nodebb/docker
    restart: unless-stopped
    ports:
      - 4567:4567
    depends_on:
      - mongo
    volumes:
      - /d/docker-volumes/nodebb/uploads:/usr/src/app/public/uploads

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /d/docker-volumes/nodebb/mongo:/data/db
