version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_phpbb
      - MARIADB_DATABASE=bitnami_phpbb
    volumes:
      - '/d/docker-volumes/phpbb/mariadb_data:/bitnami/mariadb'
  phpbb:
    image: docker.io/bitnami/phpbb:3
    restart: always
    ports:
      - '8088:8080'
      - '4433:8443'
    environment:
      - PHPBB_DATABASE_HOST=mariadb
      - PHPBB_DATABASE_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=bn_phpbb
      - PHPBB_DATABASE_NAME=bitnami_phpbb
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/d/docker-volumes/phpbb/phpbb_data:/bitnami/phpbb'
    depends_on:
      - mariadb