version: '3.1'

services:
  joomla:
    image: joomla:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8091:80
    volumes:
      - '/d/docker-volumes/joomla/joomla:/var/www/html'
      #- '/d/docker-volumes/joomla/apache2:/etc/apache2'
     
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: allen123
      JOOMLA_DB_USER: allen
      JOOMLA_DB_NAME: joomla

  db:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=root123
      - MARIADB_PASSWORD=allen123
      - MARIADB_USER=allen
      - MARIADB_DATABASE=joomla
    volumes:
      - '/d/docker-volumes/joomla/mariadb_data:/bitnami/mariadb'     